INSERT INTO CATEGORY VALUES ('phu-lieu-hoa',N'Phụ liệu hoa');
INSERT INTO CATEGORY VALUES ('hoa-chau',N'Hoa chậu');
INSERT INTO CATEGORY VALUES ('lan-ho-diep',N'Lan hồ điệp');
INSERT INTO CATEGORY VALUES ('hoa-chia-buon',N'Hoa chia buồn');
INSERT INTO CATEGORY VALUES ('ngay-phu-nu-viet-nam-20-10',N'Ngày phụ nữ Việt Nam 20/10');
INSERT INTO CATEGORY VALUES ('hoa-cat-canh',N'Hoa cắt cành');
INSERT INTO CATEGORY VALUES ('valentine',N'Valentine');
INSERT INTO CATEGORY VALUES ('hoa-tang-hoa-dich-vu',N'Hoa tặng - Hoa dịch vụ');
INSERT INTO CATEGORY VALUES ('ngay-nha-giao-viet-nam-20-11',N'Ngày nhà giáo Việt Nam 20/11');
INSERT INTO CATEGORY VALUES ('hoa-chuc-mung',N'Hoa chúc mừng');
INSERT INTO CATEGORY VALUES ('hoa-chau-thiet-ke',N'Hoa chậu thiết kế');
INSERT INTO CATEGORY VALUES ('hoa-xinh-gia-tot',N'Hoa xinh giá tốt');
INSERT INTO CATEGORY VALUES ('ngay-quoc-te-phu-nu-8-3',N'Ngày quốc tế phụ nữ 8/3');
INSERT INTO CATEGORY VALUES ('ngay-cua-cha',N'Ngày của cha');
INSERT INTO CATEGORY VALUES ('giang-sinh',N'Giáng sinh');
INSERT INTO CATEGORY VALUES ('cay-xanh',N'Cây xanh');
INSERT INTO CATEGORY VALUES ('hoa-tet',N'Hoa tết');
INSERT INTO CATEGORY VALUES ('canh-dong-hoa',N'Cánh đồng hoa');
INSERT INTO CATEGORY VALUES ('ngay-cua-me',N'Ngày của mẹ');