INSERT INTO CATEGORY VALUES ('phu-lieu-hoa','Phụ liệu hoa');
INSERT INTO CATEGORY VALUES ('hoa-chau','Hoa chậu');
INSERT INTO CATEGORY VALUES ('lan-ho-diep','Lan hồ điệp');
INSERT INTO CATEGORY VALUES ('hoa-chia-buon','Hoa chia buồn');
INSERT INTO CATEGORY VALUES ('ngay-phu-nu-viet-nam-20-10','Ngày phụ nữ Việt Nam 20/10');
INSERT INTO CATEGORY VALUES ('hoa-cat-canh','Hoa cắt cành');
INSERT INTO CATEGORY VALUES ('valentine','Valentine');
INSERT INTO CATEGORY VALUES ('hoa-tang-hoa-dich-vu','Hoa tặng - Hoa dịch vụ');
INSERT INTO CATEGORY VALUES ('ngay-nha-giao-viet-nam-20-11','Ngày nhà giáo Việt Nam 20/11');
INSERT INTO CATEGORY VALUES ('hoa-chuc-mung','Hoa chúc mừng');
INSERT INTO CATEGORY VALUES ('hoa-chau-thiet-ke','Hoa chậu thiết kế');
INSERT INTO CATEGORY VALUES ('hoa-xinh-gia-tot','Hoa xinh giá tốt');
INSERT INTO CATEGORY VALUES ('ngay-quoc-te-phu-nu-8-3','Ngày quốc tế phụ nữ 8/3');
INSERT INTO CATEGORY VALUES ('ngay-cua-cha','Ngày của cha');
INSERT INTO CATEGORY VALUES ('giang-sinh','Giáng sinh');
INSERT INTO CATEGORY VALUES ('cay-xanh','Cây xanh');
INSERT INTO CATEGORY VALUES ('hoa-tet','Hoa tết');
INSERT INTO CATEGORY VALUES ('canh-dong-hoa','Cánh đồng hoa');
INSERT INTO CATEGORY VALUES ('ngay-cua-me','Ngày của mẹ');